version: "1.0"

services:

  postgres:
    image: postgres:14.5
    volumes:
      - postgres_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mshmatov_db
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "128M"
        reservations:
          cpus: "0.1"
          memory: "64M"
volumes:
  postgres_db: